# Generated by Django 5.0.6 on 2024-05-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('time', models.DateTimeField(blank=True)),
                ('time_seconds', models.PositiveIntegerField()),
            ],
        ),
    ]
